name: Test
on:
  pull_request:
    branches-ignore:
      - main
    paths:
      - '**.go'
  push:
    branches-ignore:
      - main
    paths:
      - '**.go'
jobs:
  go-test:
    runs-on: ubuntu-latest
    env:
      FUNCTION_NAME: '${{ secrets.FUNCTION_NAME }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'
      TF_TOKEN: '${{ secrets.TF_TOKEN }}'
      BUCKET: '${{ secrets.BUCKET }}'
      GH_TOKEN: '${{ secrets.GH_TOKEN }}'

    steps:
      - name: Setup actions/checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3

      - name: Go FMT
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          go fmt ./...
          git add .
          git commit -m "github action: go fmt"
          git push
        continue-on-error: true
        working-directory: main

      - name: Test Golang Code
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0
          go mod tidy
          go test -v ./...
        working-directory: main